# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      pip:
        patterns:
          - "*"
